<a href="https://colab.research.google.com/github/KhmAsif/IMSE441Spring24/blob/main/Data_Cleaning%26Preparation_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt

# Data upload

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/IMSE_441/dataset_olympics.csv')

In [ ]:
data

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,35656,Stuart Fitzsimmons,M,19.0,NaN,NaN,Great Britain,GBR,1976 Winter,1976,Winter,Innsbruck,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
69996,35656,Stuart Fitzsimmons,M,19.0,NaN,NaN,Great Britain,GBR,1976 Winter,1976,Winter,Innsbruck,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
69997,35657,"David Thomas ""Dave"" Fitzsimons",M,26.0,170.0,65.0,Australia,AUS,1976 Summer,1976,Summer,Montreal,Athletics,"Athletics Men's 10,000 metres",NaN
69998,35657,"David Thomas ""Dave"" Fitzsimons",M,30.0,170.0,65.0,Australia,AUS,1980 Summer,1980,Summer,Moskva,Athletics,"Athletics Men's 5,000 metres",NaN
69999,35658,Marek Fiurek,M,23.0,180.0,68.0,Czech Republic,CZE,1998 Winter,1998,Winter,Nagano,Nordic Combined,Nordic Combined Men's Team,NaN

# Data type check

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      70000 non-null  int64
 1   Name    70000 non-null  object
 2   Sex     70000 non-null  object
 3   Age     67268 non-null  float64
 4   Height  53746 non-null  float64
 5   Weight  52899 non-null  float64
 6   Team    70000 non-null  object
 7   NOC     70000 non-null  object
 8   Games   70000 non-null  object
 9   Year    70000 non-null  int64
 10  Season  70000 non-null  object
 11  City    70000 non-null  object
 12  Sport   70000 non-null  object
 13  Event   70000 non-null  object
 14  Medal   9690 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 8.0+ MB

# Data type modification

In [ ]:
data['Year']=data['Year'].astype(object)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      70000 non-null  int64
 1   Name    70000 non-null  object
 2   Sex     70000 non-null  object
 3   Age     67268 non-null  float64
 4   Height  53746 non-null  float64
 5   Weight  52899 non-null  float64
 6   Team    70000 non-null  object
 7   NOC     70000 non-null  object
 8   Games   70000 non-null  object
 9   Year    70000 non-null  object
 10  Season  70000 non-null  object
 11  City    70000 non-null  object
 12  Sport   70000 non-null  object
 13  Event   70000 non-null  object
 14  Medal   9690 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 8.0+ MB

In [ ]:
data['Year']=data['Year'].astype(float)

# **Data selection**

In [ ]:
data=data[data['Year']>2000]

In [ ]:
data

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
28,9,Antti Sami Aalto,M,26.0,186.0,96.0,Finland,FIN,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
40,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze
72,20,Kjetil Andr Aamodt,M,30.0,176.0,85.0,Norway,NOR,2002 Winter,2002,Winter,Salt Lake City,Alpine Skiing,Alpine Skiing Men's Downhill,NaN
73,20,Kjetil Andr Aamodt,M,30.0,176.0,85.0,Norway,NOR,2002 Winter,2002,Winter,Salt Lake City,Alpine Skiing,Alpine Skiing Men's Super G,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69988,35653,Casey J. FitzRandolph,M,27.0,180.0,79.0,United States,USA,2002 Winter,2002,Winter,Salt Lake City,Speed Skating,Speed Skating Men's 500 metres,Gold
69989,35653,Casey J. FitzRandolph,M,27.0,180.0,79.0,United States,USA,2002 Winter,2002,Winter,Salt Lake City,Speed Skating,"Speed Skating Men's 1,000 metres",NaN
69990,35653,Casey J. FitzRandolph,M,31.0,180.0,79.0,United States,USA,2006 Winter,2006,Winter,Torino,Speed Skating,Speed Skating Men's 500 metres,NaN
69991,35653,Casey J. FitzRandolph,M,31.0,180.0,79.0,United States,USA,2006 Winter,2006,Winter,Torino,Speed Skating,"Speed Skating Men's 1,000 metres",NaN
69993,35655,Riley Fitzsimmons,M,20.0,192.0,93.0,Australia,AUS,2016 Summer,2016,Summer,Rio de Janeiro,Canoeing,"Canoeing Men's Kayak Fours, 1,000 metres",NaN

In [ ]:
data=data.iloc[0:100,0:10]

In [ ]:
data

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988
...,...,...,...,...,...,...,...,...,...,...
95,32,Olav Augunson Aarnes,M,23.0,NaN,NaN,Norway,NOR,1912 Summer,1912
96,33,Mika Lauri Aarnikka,M,24.0,187.0,76.0,Finland,FIN,1992 Summer,1992
97,33,Mika Lauri Aarnikka,M,28.0,187.0,76.0,Finland,FIN,1996 Summer,1996
98,34,Jamale (Djamel-) Aarrass (Ahrass-),M,30.0,187.0,76.0,France,FRA,2012 Summer,2012
99,35,Dagfinn Sverre Aarskog,M,24.0,190.0,98.0,Norway,NOR,1998 Winter,1998

In [ ]:
data.drop(['NOC','Team','Games'], axis=1)

    ID                                Name Sex   Age  Height  Weight  Year
0    1                           A Dijiang   M  24.0   180.0    80.0  1992
1    2                            A Lamusi   M  23.0   170.0    60.0  2012
4    5            Christine Jacoba Aaftink   F  21.0   185.0    82.0  1988
5    5            Christine Jacoba Aaftink   F  21.0   185.0    82.0  1988
6    5            Christine Jacoba Aaftink   F  25.0   185.0    82.0  1992
..  ..                                 ...  ..   ...     ...     ...   ...
94  31                   Evald rma (rman-)   M  24.0   174.0    70.0  1936
96  33                 Mika Lauri Aarnikka   M  24.0   187.0    76.0  1992
97  33                 Mika Lauri Aarnikka   M  28.0   187.0    76.0  1996
98  34  Jamale (Djamel-) Aarrass (Ahrass-)   M  30.0   187.0    76.0  2012
99  35              Dagfinn Sverre Aarskog   M  24.0   190.0    98.0  1998

[81 rows x 7 columns]

# Removing duplicates and null values

In [ ]:
data.isnull()

       ID   Name    Sex    Age  Height  Weight   Team    NOC  Games   Year
0   False  False  False  False   False   False  False  False  False  False
1   False  False  False  False   False   False  False  False  False  False
2   False  False  False  False    True    True  False  False  False  False
3   False  False  False  False    True    True  False  False  False  False
4   False  False  False  False   False   False  False  False  False  False
..    ...    ...    ...    ...     ...     ...    ...    ...    ...    ...
95  False  False  False  False    True    True  False  False  False  False
96  False  False  False  False   False   False  False  False  False  False
97  False  False  False  False   False   False  False  False  False  False
98  False  False  False  False   False   False  False  False  False  False
99  False  False  False  False   False   False  False  False  False  False

[100 rows x 10 columns]

In [ ]:
data = data.dropna()

In [ ]:
data

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992
...,...,...,...,...,...,...,...,...,...,...
94,31,Evald rma (rman-),M,24.0,174.0,70.0,Estonia,EST,1936 Summer,1936
96,33,Mika Lauri Aarnikka,M,24.0,187.0,76.0,Finland,FIN,1992 Summer,1992
97,33,Mika Lauri Aarnikka,M,28.0,187.0,76.0,Finland,FIN,1996 Summer,1996
98,34,Jamale (Djamel-) Aarrass (Ahrass-),M,30.0,187.0,76.0,France,FRA,2012 Summer,2012
99,35,Dagfinn Sverre Aarskog,M,24.0,190.0,98.0,Norway,NOR,1998 Winter,1998

In [ ]:
data=data.drop(['NOC','Team','Games'], axis=1)

In [ ]:
data

    ID                                Name Sex   Age  Height  Weight  Year
0    1                           A Dijiang   M  24.0   180.0    80.0  1992
1    2                            A Lamusi   M  23.0   170.0    60.0  2012
4    5            Christine Jacoba Aaftink   F  21.0   185.0    82.0  1988
5    5            Christine Jacoba Aaftink   F  21.0   185.0    82.0  1988
6    5            Christine Jacoba Aaftink   F  25.0   185.0    82.0  1992
..  ..                                 ...  ..   ...     ...     ...   ...
94  31                   Evald rma (rman-)   M  24.0   174.0    70.0  1936
96  33                 Mika Lauri Aarnikka   M  24.0   187.0    76.0  1992
97  33                 Mika Lauri Aarnikka   M  28.0   187.0    76.0  1996
98  34  Jamale (Djamel-) Aarrass (Ahrass-)   M  30.0   187.0    76.0  2012
99  35              Dagfinn Sverre Aarskog   M  24.0   190.0    98.0  1998

[81 rows x 7 columns]

In [ ]:
data.drop_duplicates()

    ID                                Name Sex   Age  Height  Weight  Year
0    1                           A Dijiang   M  24.0   180.0    80.0  1992
1    2                            A Lamusi   M  23.0   170.0    60.0  2012
4    5            Christine Jacoba Aaftink   F  21.0   185.0    82.0  1988
6    5            Christine Jacoba Aaftink   F  25.0   185.0    82.0  1992
8    5            Christine Jacoba Aaftink   F  27.0   185.0    82.0  1994
10   6                     Per Knut Aaland   M  31.0   188.0    75.0  1992
14   6                     Per Knut Aaland   M  33.0   188.0    75.0  1994
18   7                        John Aalberg   M  31.0   183.0    72.0  1992
22   7                        John Aalberg   M  33.0   183.0    72.0  1994
28   9                    Antti Sami Aalto   M  26.0   186.0    96.0  2002
30  11                  Jorma Ilmari Aalto   M  22.0   182.0    76.5  1980
31  12                   Jyri Tapani Aalto   M  31.0   172.0    70.0  2000
32  13                  Minna Maarit Aalto   F  30.0   159.0    55.5  1996
33  13                  Minna Maarit Aalto   F  34.0   159.0    55.5  2000
34  14      Pirjo Hannele Aalto (Mattila-)   F  32.0   171.0    65.0  1994
40  16            Juhamatti Tapio Aaltonen   M  28.0   184.0    85.0  2014
41  17             Paavo Johannes Aaltonen   M  28.0   175.0    64.0  1948
49  17             Paavo Johannes Aaltonen   M  32.0   175.0    64.0  1952
57  18                Timo Antero Aaltonen   M  31.0   189.0   130.0  2000
59  20                  Kjetil Andr Aamodt   M  20.0   176.0    85.0  1992
63  20                  Kjetil Andr Aamodt   M  22.0   176.0    85.0  1994
68  20                  Kjetil Andr Aamodt   M  26.0   176.0    85.0  1998
72  20                  Kjetil Andr Aamodt   M  30.0   176.0    85.0  2002
77  20                  Kjetil Andr Aamodt   M  34.0   176.0    85.0  2006
80  22                       Andreea Aanei   F  22.0   170.0   125.0  2016
81  23                         Fritz Aanes   M  22.0   187.0    89.0  2000
82  23                         Fritz Aanes   M  26.0   187.0    89.0  2004
87  26        Agnes Erika Aanonsen (-Eyde)   F  17.0   169.0    65.0  1984
89  28                    Jan-Erik Aarberg   M  43.0   170.0    77.0  1968
90  28                    Jan-Erik Aarberg   M  47.0   170.0    77.0  1972
92  30                    Pepijn Aardewijn   M  26.0   189.0    72.0  1996
93  30                    Pepijn Aardewijn   M  30.0   189.0    72.0  2000
94  31                   Evald rma (rman-)   M  24.0   174.0    70.0  1936
96  33                 Mika Lauri Aarnikka   M  24.0   187.0    76.0  1992
97  33                 Mika Lauri Aarnikka   M  28.0   187.0    76.0  1996
98  34  Jamale (Djamel-) Aarrass (Ahrass-)   M  30.0   187.0    76.0  2012
99  35              Dagfinn Sverre Aarskog   M  24.0   190.0    98.0  1998

In [ ]:
data = data.reset_index()

In [ ]:
data

,index,ID,Name,Sex,Age,Height,Weight,Year
0,0,1,A Dijiang,M,24.0,180.0,80.0,1992
1,1,2,A Lamusi,M,23.0,170.0,60.0,2012
2,4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,1988
3,5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,1988
4,6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,1992
...,...,...,...,...,...,...,...,...
76,94,31,Evald rma (rman-),M,24.0,174.0,70.0,1936
77,96,33,Mika Lauri Aarnikka,M,24.0,187.0,76.0,1992
78,97,33,Mika Lauri Aarnikka,M,28.0,187.0,76.0,1996
79,98,34,Jamale (Djamel-) Aarrass (Ahrass-),M,30.0,187.0,76.0,2012
80,99,35,Dagfinn Sverre Aarskog,M,24.0,190.0,98.0,1998